events {}

http {
    upstream app_servers {
        server spring_rc_app_1:8080;
        server spring_rc_app_2:8080;
        server spring_rc_app_3:8080;
        server spring_rc_app_4:8080;
        server spring_rc_app_5:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://app_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header X-Upstream-Server $upstream_addr always;
        }
    }
}
